FROM node:latest As builder
WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod

FROM httpd:latest

COPY --from=builder /usr/src/app/dist/ /var/www/html/