image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - master
  script:
    - cd ./CosiamClientApp
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod
    - cp ./dist/index.html ./dist/200.html
    - ./node_modules/.bin/surge -p dist --domain cosiam-stage.surge.sh

deploy_production:
  stage: deploy
  environment: Production
  only:
    - tags
  script:
    - cd ./CosiamClientApp
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod
    - cp ./dist/index.html ./dist/200.html
    - ./node_modules/.bin/surge -p dist --domain cosiam.surge.sh
