export let usersListData = [
  {
    ID: 300,
    Username: 'dean3004',
    avatar: 'avatar-s-10.png',
    Name: 'Francesco Greco',
    'Last Activity': '2019/04/30',
    Role: 'Amministratore',
    Status: 'Attivo',
    Edit: '',
  },
  {
    ID: 301,
    Username: 'zena0604',
    avatar: 'avatar-s-1.png',
    Name: 'Mario Loro',
    'Last Activity': '2020/04/06',
    Role: 'Utente',
    Status: 'Attivo',
    Edit: '',
  },
  {
    ID: 302,
    Username: 'delilah0301',
    avatar: 'avatar-s-9.png',
    Name: 'Laura Pore',
    'Last Activity': '2020/01/03',
    Role: 'Utente',
    Status: 'Disabilitato',
    Edit: '',
  },
  {
    ID: 303,
    Username: 'hillary1807',
    avatar: 'avatar-s-10.png',
    Name: 'Ilaria More',
    'Last Activity': '2019/07/18',
    Role: 'Utente',
    Status: 'Attivo',
    Edit: '',
  },
  {
    ID: 304,
    Username: 'herman2003',
    avatar: 'avatar-s-16.png',
    Name: 'Giuseppe Sasso',
    'Last Activity': '2020/03/20',
    Role: 'Capocantiere',
    Status: 'Disabilitato',
    Edit: '',
  },
  ];
